### ISSUE TITLE
Pretrained weights link (GoogleDrive) not accessible.

### ISSUE THREAD

**Issue by importnumpy** [KU-CVLAB/3DGAN-Inversion#1]
Hello! 
I was hoping to test your model's but the Google Drive link to a pre-trained weight link throws an 404 error.
Can I ask you to confirm?

**Comment by kyusuncho** [comment]
Hi. Sorry about that. 
We are in the middle of a server migration. We plan to notify the updated download link at Wednesday evening. 
Sorry for the inconvenience.

**Comment by mlnyang** [comment]
We replaced the download link to new one.
Thanks for your comment! :)
