### ISSUE TITLE
No such file or directory: ./initializer/model_ir_se50.pth

### ISSUE THREAD

**Issue by truonglengocncc** [KU-CVLAB/3DGAN-Inversion#11]
I followed the steps, after downloading the file on GG Driver. I ran the reverse process: "python scripts/run_pti.py" and got the error:
FileNotFoundError: [Errno 2] No such file or directory: './initializer/model_ir_se50.pth'

![image](https://github.com/KU-CVLAB/3DGAN-Inversion/assets/144106450/e1278895-f487-49c3-bc63-e4b660a6b028)

**Comment by truonglengocncc** [comment]
https://github.com/omertov/encoder4editing/issues/5

**Comment by truonglengocncc** [comment]
after add the model_ir_se50.pth file, i ran it with comman "Python script/run_pti.py. Then it downloads some things. But failed to set up the PyTorch plugin "bias_act_plugin"

![image](https://github.com/KU-CVLAB/3DGAN-Inversion/assets/144106450/c4ea7d8b-e381-4b85-96e2-8eca6aadd6a7)

**Comment by tbertucc** [comment]
Hello, I'm also running into this and now having the Bias_Act_Plugin failure.  I didn't see a resolution to that - anything you can share as I troubleshoot?

**Comment by truonglengocncc** [comment]
> Hello, I'm also running into this and now having the Bias_Act_Plugin failure. I didn't see a resolution to that - anything you can share as I troubleshoot?

Have you installed CUDA according to their requirements?

**Comment by tbertucc** [comment]
> > Hello, I'm also running into this and now having the Bias_Act_Plugin failure. I didn't see a resolution to that - anything you can share as I troubleshoot?
> 
> Have you installed CUDA according to their requirements?

I thought I followed the instructions with version - I had to manually build the env because the yml file was erroring out for me.  However this seems to suggest it isn't hitting the right version of CUDA, correct?  I'm remembering that I had issues getting pytorch to run with CUDA and I had to reinstall pytorch, maybe that is what happened.
![image](https://github.com/KU-CVLAB/3DGAN-Inversion/assets/26467753/5d7f7f28-b1db-40a6-9231-a5d2c6bd96e2)

**Comment by tbertucc** [comment]
I have tried installing cuda and pytorch specifying version 11.3 for cuda and torch 1.11 and continue to get the bias_act_plugin error. About to abandon this.  I should mention I'm on windows and using anaconda for environment manager.

**Comment by truonglengocncc** [comment]
> I have tried installing cuda and pytorch specifying version 11.3 for cuda and torch 1.11 and continue to get the bias_act_plugin error. About to abandon this. I should mention I'm on windows and using anaconda for environment manager.

![image](https://github.com/KU-CVLAB/3DGAN-Inversion/assets/144106450/0cd2a6f6-f5f0-4849-a290-14c09cf84677)
After I used the correct version of cuda toolkit and pytorch it worked normally
