### ISSUE TITLE
seek to generate data

### ISSUE THREAD

**Issue by zhou431496** [KU-CVLAB/3DGAN-Inversion#2]
Congratulations on getting such an excellent job, could you please give me a copy of the generated data, if you can, we will be very grateful, and we will also cite such excellent work in our future work.

**Comment by mlnyang** [comment]
We deleted the pseudo dataset... but you can generate it with ./script/gen_pseudo_dataset.py
such as : script/gen_pseudo_dataset.py --seeds 0-9999 --trunc 0.7 --network initializer/pretrained_models/afhqcats512-128.pkl

sorry for the inconvenience.

**Comment by zhou431496** [comment]
Thank you, I just tested the following, and it doesn't work in the win10 environment. The following problem occurs if m := range_re.match(p):^SyntaxError: invalid syntax.

**Comment by mlnyang** [comment]
The python version may cause that error. Try it on python >= 3.8 
Please let me know again if it does not work.

Best,
Jaehoon

-----Original Message-----
