### ISSUE TITLE
Image Alignment

### ISSUE THREAD

**Issue by iceli1007** [KU-CVLAB/3DGAN-Inversion#4]
Thanks for your excellent job

When I use the provided easy-to-use image alignment notebook, I got the wrong image that exists with a black border

![2](https://user-images.githubusercontent.com/49896026/219580365-b99b2879-f334-47e0-907a-44b751ea1925.png)

I need more help.

Thanks

**Comment by mlnyang** [comment]
The black border happens when the given image is not wide enough.
We followed the preprocessing code from PGGAN, which does mirror padding and blurring for the edge area. (check PGGAN and our paper's supplement)
I'll share our padding code if you give me your email address.

**Comment by iceli1007** [comment]
Thanks for your reply.

my email address is iceli@mail.ustc.edu.cn

**Comment by prraoo** [comment]
@mlnyang I have similar problem with image border, would be helpful if you could share the padding script with me as well. 

My mail id: pramod_rao@outlook.com

**Comment by luchaoqi** [comment]
@mlnyang would be great if you could share the code to lqi@cs.unc.edu

**Comment by mlnyang** [comment]
@luchaoqi Is the email address correct? Mail is not being sent to you

**Comment by luchaoqi** [comment]
> @luchaoqi Is the email address correct? Mail is not being sent to you

Corrected, sorry for the mistake
