### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by luchaoqi** [KU-CVLAB/3DGAN-Inversion#5]
Hello,

To train a custom dataset, I wanted to know if you could provide the `train.py` file for training with custom dataset like eg3d does [here](https://github.com/NVlabs/eg3d#training)? I guess I should be following the eg3d training scheme and specifying the trained eg3d model in PTI's config file. But would be happy to hear your suggestions.

Also in the paper it mentioned that:
> We also use the pre-trained weights on the AFHQ dataset [8] for cat faces and evaluate on the AnimalFace10 dataset [31].

Does that mean you feed the pre-trained model into PTI? Could you give more details or explain the pipeline a bit? Thanks so much for the help!

**Comment by mlnyang** [comment]
We don't have a code for training the generator network. 

> We also use the pre-trained weights on the AFHQ dataset [8] for cat faces and evaluate on the AnimalFace10 dataset [31].

This means that we just used a pre-trained generator checkpoint from EG3D repo (trained on AFHQ).

Is the custom dataset you mentioned out of domain(not human face or cat face) images? 
If you want to try on the OOD custom dataset, you can follow the EG3D training code to create your own checkpoint.

**Comment by luchaoqi** [comment]
Thanks so much for the reply! that makes sense to me.
