### ISSUE TITLE
3d shape and depth map extraction 

### ISSUE THREAD

**Issue by juanjomon** [KU-CVLAB/3DGAN-Inversion#6]
First, congrats for your interesting work,  but I have a question:
 
How can I get the 3d shape in mrc file from a given photo that has been inverted? So far the output is only a mp4 video. How can I get the correspondent 3d shape? (as  the ones generated with gen_samples from the ffhq pkl).

On the other hand.. is it possible to obtain the depth map video as the one you display in your project website aside the image video?.

Any help would be much appreciated.

Thanks.

**Comment by mlnyang** [comment]
Hi thinks for your comment!

We haven't try on generating video from mrc file, but this issue may help you.
-> https://github.com/NVlabs/eg3d/issues/66

For the depth map video, you can just utilize the video generation code https://github.com/KU-CVLAB/3DGAN-Inversion/blob/3cfebf9abc0733aae5c5e512f33ce18d016e3e48/training/coaches/single_id_coach.py#L62 
and change the image_mode = 'image_depth' in [here](https://github.com/KU-CVLAB/3DGAN-Inversion/blob/3cfebf9abc0733aae5c5e512f33ce18d016e3e48/gen_videos.py#L126)

**Comment by juanjomon** [comment]
thanks.
